---
config:
  version: 1.0
code:
  local_id: autocontext_mr_ct
  url: https://www.dropbox.com/s/746d45nkk41enjz/autocontext_mr_ct_model_zoo_config.tar.gz?dl=1
  action: expand
  destination: extensions
